%% ========================================================================
%  LITHIUM FORMATE DOE — RUN SCRIPT
%  ========================================================================
%  Creates a Design of Experiments for lithium formate synthesis.
%
%  FACTORS
%    Mode          (Categorical)  : Co-only, Mn-only, Together
%    Temperature   (Continuous)   : 60–90 °C
%    Time          (Continuous)   : 30–180 min
%    Concentration (Continuous)   : 0.20–1.00 M
%    S/L Ratio     (Continuous)   : 0.02–0.20 g/mL
%
%  Uses a cell array for factors because categorical and continuous
%  structs have different fields.
%  ========================================================================
clear; clc; close all;

%% 1. DEFINE FACTORS
% -------------------------------------------------------------------------
% Use a cell array — each element is a struct with only the fields it needs.

factors = {
    struct('name', 'Mode', ...
           'type', 'categorical', ...
           'levels', ["Co-only", "Mn-only", "Together"])

    struct('name', 'Temperature', ...
           'type', 'continuous', ...
           'low',  60, ...
           'high', 90, ...
           'units', 'degC')

    struct('name', 'Time', ...
           'type', 'continuous', ...
           'low',  30, ...
           'high', 180, ...
           'units', 'min')

    struct('name', 'Concentration', ...
           'type', 'continuous', ...
           'low',  0.20, ...
           'high', 1.00, ...
           'units', 'M')

    struct('name', 'SLRatio', ...
           'type', 'continuous', ...
           'low',  0.02, ...
           'high', 0.20, ...
           'units', 'g/mL')
};

%% 2. (OPTIONAL) DEFINE CONSTRAINTS
% -------------------------------------------------------------------------
% Each function receives the run-sheet TABLE and returns a logical vector:
%   true  = keep the run
%   false = discard the run

constraints = {};
% Uncomment / adapt as needed:
% constraints{1} = @(T) ~(T.Temperature > 85 & T.Concentration > 0.8);
% constraints{2} = @(T) ~(strcmp(string(T.Mode), "Together") & T.Time < 60);

%% 3. CREATE THE DOE
% -------------------------------------------------------------------------
% Pick ONE design type by uncommenting the corresponding block.

% ── Option A: CCD (rotatable) ──────────────────────────────────────────
[design, report, cfg] = createDOE(factors, ...
    'type',          'ccd', ...
    'numBlocks',      4, ...
    'ccdAlpha',      'rotatable', ...   % alpha = 2^(k/4)
    'centerPoints',  6, ...
    'replicates',    1, ...
    'randomize',     true, ...
    'randomSeed',    42, ...
    'constraints',   constraints, ...
    'projectName',   'LithiumFormate_CCD', ...
    'title',         'Lithium Formate Synthesis', ...
    'owner',         'Casimir', ...
    'notes',         'CCD for lithium formate leaching optimisation', ...
    'exportCSV',     true, ...
    'exportMAT',     true, ...
    'exportFolder',  './DOE_Output', ...
    'responses',     {'Yield_pct', 'Purity_pct'});

% ── Option B: Box–Behnken (fewer runs) ─────────────────────────────────
% [design, report, cfg] = createDOE(factors, ...
%     'type','bbd', 'centerPoints',5, 'randomize',true, 'randomSeed',42, ...
%     'projectName','LithiumFormate_BBD', 'exportCSV',true);

% ── Option C: Full factorial (all interactions) ─────────────────────────
% [design, report, cfg] = createDOE(factors, ...
%     'type','fullfact', 'centerPoints',3, 'randomize',true, ...
%     'projectName','LithiumFormate_FF', 'exportCSV',true);

%% 4. DISPLAY SUMMARY
% -------------------------------------------------------------------------
%fprintf('%s\n', report.summaryText); % Not required since I forgor I
%already print it.

%% 5. PREVIEW RUN SHEET
% -------------------------------------------------------------------------
fprintf('RUN SHEET PREVIEW (first 10 rows)\n');
fprintf('========================================\n');
disp(design.runSheet(1:min(10, height(design.runSheet)), :));

%% 6. NOTES
% -------------------------------------------------------------------------
% CCD with 4 continuous factors:
%   2^4 = 16 factorial + 2×4 = 8 axial + 6 center = 30 base runs
%   × 3 categorical levels (Mode) = 90 total runs
%
% BBD with 4 continuous factors:
%   6 pairs × 4 + 1 center = 25 base + extra centers
%   × 3 categorical levels = ~80–90 runs (fewer than CCD)
%
% NEXT STEPS
%   1. Open DOE_Output/<project>_runsheet.csv
%   2. Run experiments in the randomised order
%   3. Fill in the response columns
%   4. Fit a model:
%        mdl = fitlm(design.runSheet, 'Yield_pct ~ Temperature*Time*Concentration');
