%% ========================================================================
%  EXAMPLE RUNSCRIPT — Polymer Coating Adhesion Study
%  ========================================================================
%  A made-up experiment to demonstrate createDOE usage.
%
%  Scenario: optimising adhesion strength of a polymer coating.
%  We want to test three curing methods (categorical) against four
%  continuous process parameters.
%  ========================================================================
clear; clc; close all;

%% 1. DEFINE FACTORS
% -------------------------------------------------------------------------
% Cell array because we're mixing categorical and continuous.

factors = {
    struct('name', 'CureMethod', ...
           'type', 'categorical', ...
           'levels', ["UV", "Thermal", "Hybrid"])

    struct('name', 'Temperature', ...
           'type', 'continuous', ...
           'low',  80, ...
           'high', 160, ...
           'units', 'degC')

    struct('name', 'CoatThickness', ...
           'type', 'continuous', ...
           'low',  10, ...
           'high', 50, ...
           'units', 'um')

    struct('name', 'DwellTime', ...
           'type', 'continuous', ...
           'low',  5, ...
           'high', 60, ...
           'units', 'min')

    struct('name', 'SurfaceRoughness', ...
           'type', 'continuous', ...
           'low',  0.1, ...
           'high', 2.0, ...
           'units', 'um')
};

%% 2. CONSTRAINTS
% -------------------------------------------------------------------------
constraints = {};
% UV curing doesn't work above 130 degC
constraints{1} = @(T) ~(string(T.CureMethod) == "UV" & T.Temperature > 130);

%% 3a. OPTION A — BBD with categorical ENCODED (compact, 41 base runs)
% -------------------------------------------------------------------------
% Treats CureMethod as a 3-level coded factor inside the BBD.
% This is the more economical option.

[design_enc, report_enc] = createDOE(factors, ...
    'type',         'bbd', ...
    'catMethod',    'encode', ...
    'centerPoints', 3, ...
    'randomize',    true, ...
    'randomSeed',   7, ...
    'constraints',  constraints, ...
    'projectName',  'Adhesion_BBD_encoded', ...
    'title',        'Polymer Adhesion (encoded)', ...
    'responses',    {'AdhesionStrength_MPa', 'Uniformity_pct'});

%% 3b. OPTION B — BBD with categorical CROSSED (full design per level)
% -------------------------------------------------------------------------
% Builds the BBD for continuous factors only, then repeats it for each
% CureMethod.  More runs, but each level gets independent coverage.

[design_cross, report_cross] = createDOE(factors, ...
    'type',         'bbd', ...
    'catMethod',    'cross', ...
    'centerPoints', 3, ...
    'randomize',    true, ...
    'randomSeed',   7, ...
    'constraints',  constraints, ...
    'projectName',  'Adhesion_BBD_crossed', ...
    'title',        'Polymer Adhesion (crossed)', ...
    'responses',    {'AdhesionStrength_MPa', 'Uniformity_pct'});

%% 3c. OPTION C — BBD+CCD hybrid (BBD core + axial augmentation)
% -------------------------------------------------------------------------
% Starts from a BBD, then adds CCD axial (star) points for better
% quadratic estimation at the extremes.

[design_hyb, report_hyb] = createDOE(factors, ...
    'type',         'bbd_ccd', ...
    'catMethod',    'encode', ...
    'ccdAlpha',     'rotatable', ...
    'centerPoints', 3, ...
    'randomize',    true, ...
    'randomSeed',   7, ...
    'constraints',  constraints, ...
    'projectName',  'Adhesion_BBDCCD', ...
    'title',        'Polymer Adhesion (BBD+CCD hybrid)', ...
    'responses',    {'AdhesionStrength_MPa', 'Uniformity_pct'});

%% 4. COMPARE RUN COUNTS
% -------------------------------------------------------------------------
fprintf('\n========================================\n');
fprintf(' RUN COUNT COMPARISON\n');
fprintf('========================================\n');
fprintf('  BBD encoded:  %d runs\n', report_enc.nRuns);
fprintf('  BBD crossed:  %d runs\n', report_cross.nRuns);
fprintf('  BBD+CCD hyb:  %d runs\n', report_hyb.nRuns);
fprintf('========================================\n\n');

%% 5. PREVIEW
% -------------------------------------------------------------------------
fprintf('Encoded BBD — first 10 rows:\n');
disp(design_enc.runSheet(1:min(10, height(design_enc.runSheet)), :));